export const investigadores = [
  {
    name: "Dr. Konstantin Starkov",
    email: "konst@citedi.mx",
    level: "III",
    id: 1,
  },
  {
    name: "Dr. Eduardo Javier Moreno Valenzuela",
    email: "moreno@citedi.mx",
    level: "III",
    id: 2,
  },
  {
    name: "Dr. Luis Tupak Aguilar Bustos",
    email: "laguilar@citedi.mx",
    level: "II",
    id: 3,
  },
  {
    name: "Dr. Oscar Humberto Montiel Ross",
    email: "oross@citedi.mx",
    level: "II",
    id: 4,
  },
  {
    name: "Dr. José Cruz Núñez Pérez",
    email: "nunez@citedi.mx",
    level: "II",
    id: 5,
  },
  {
    name: "Dr. Víctor Hugo Díaz Ramírez",
    email: "vhdiaz@citedi.mx",
    level: "II",
    id: 6,
  },
  {
    name: "Dr. Rigoberto Juárez Salazar",
    email: "rjuarez@citedi.mx",
    level: "II",
    id: 7,
  },
  {
    name: "Dra. Mireya Saraí García Vázquez",
    email: "mgarciav@citedi.mx",
    level: "I",
    id: 8,
  },
  {
    name: "Dr. Juan José Tapia Armenta",
    email: "jjtapia@citedi.mx",
    level: "I",
    id: 9,
  },
  {
    name: "Dr. Sergio Jesús González Ambriz",
    email: "sgonzalez@citedi.mx",
    level: "C",
    id: 10,
  },
  {
    name: "Dr. Luis Arturo González Hernández",
    email: "lgonzal@citedi.mx",
    level: "",
    id: 11,
  },
  {
    name: "Dr. Ciro Andrés Martínez García Moreno",
    email: "ciro@citedi.mx",
    level: "",
    id: 12,
  },
  {
    name: "Dr. Julio César Rolón Garrido",
    email: "jcrolon@citedi.mx",
    level: "",
    id: 13,
  },
  {
    name: "Dr. Roberto Herrera Charles",
    email: "robccharles@citedi.mx",
    level: "",
    id: 14,
  },
  {
    name: "Dr. Moisés Sánchez Adame",
    email: "msanchez@citedi.mx",
    level: "",
    id: 15,
  },
  {
    name: "Dra. Isaura González Rubio Acosta",
    email: "isaura@citedi.mx",
    level: "",
    id: 16,
  },
  {
    name: "M. en C. Teodoro Álvarez Sánchez",
    email: "talvarez@citedi.mx",
    level: "",
    id: 17,
  },
  {
    name: "M. en C. Adolfo Esquivel Martínez",
    email: "esquivel@citedi.mx",
    level: "",
    id: 18,
  },
  {
    name: "M. en C. David Jaime Saucedo Martínez",
    email: "dsaucedo@citedi.mx",
    level: "",
    id: 19,
  },
  {
    name: "M. en C. Andrés Calvillo Téllez",
    email: "calvillo@citedi.mx",
    level: "",
    id: 20,
  },
  {
    name: "M. en C. Luis Miguel Zamudio Fuentes",
    email: "lmzamudio@citedi.mx",
    level: "",
    id: 21,
  },
  {
    name: "Esp. Eduardo Barba Cervantes",
    email: "ebarba@citedi.mx",
    level: "",
    id: 22,
  },
];
